// fourth-challenge/resources/js/components/modals/DeleteFlight.jsx
import React, { useContext } from 'react'
import AppContext from '../../context/AppContext'
import Button from '../Button'

const DeleteFlight = () => {
    const { deleteFlight, setDeleteModal, deleteModal,updateFlights } = useContext(AppContext)
    console.log(deleteFlight)



    const handleDeleteFlight = async () => {
        const res = await axios.delete(`/manage/flights/${deleteFlight.id}`
        ).then(res => {
           updateFlights(deleteFlight,"delete");
           setDeleteModal(!deleteModal)
        })
    }
    return (
        <div>
            <div className="flex justify-end " onClick={() => setDeleteModal(!deleteModal)}>
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
            </div>
            <h2 className="my-2 ">Do you want to delete <strong>{deleteFlight.company.name}</strong>'s flight with destination <strong>{deleteFlight.destination.name}</strong> ?</h2>
            <div className='full flex'>
                <Button type={"secondary"} text={"Cancel"} onClick={() => { setDeleteModal(!deleteModal) }} />
                <Button type={"primary"} text={"Delete"} onClick={handleDeleteFlight} />
            </div>
        </div>
    )
}

export default DeleteFlight

// fourth-challenge/resources/js/components/DeleteFlight.vue
<template>
    <div
        class="overflow-y-auto overflow-x-hidden fixed right-0 left-0 top-4 z-50 justify-center items-center md:inset-0 h-modal sm:h-full flex h-screen"
        id="popup-modal"
        aria-hidden="true"
    >
        <div class="relative px-4 w-full max-w-md h-full md:h-auto">
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <div class="flex justify-end p-2">
                    <button
                        type="button"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white"
                        data-modal-toggle="popup-modal"
                        @click="closePanel"
                    >
                        <svg
                            class="w-5 h-5"
                            fill="currentColor"
                            viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <path
                                fill-rule="evenodd"
                                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                clip-rule="evenodd"
                            ></path>
                        </svg>
                    </button>
                </div>

                <div class="p-6 pt-0 text-center">
                    <svg
                        class="mx-auto mb-4 w-14 h-14 text-gray-400 dark:text-gray-200"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                        ></path>
                    </svg>
                    <h3
                        class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400"
                    >
                        Are you sure you want to delete this flight? Flight id:
                        {{ flight.id }}
                    </h3>
                    <button
                        data-modal-toggle="popup-modal"
                        type="button"
                        class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2"
                        @click="deleteFlight"
                    >
                        Yes, I'm sure
                    </button>
                    <button
                        data-modal-toggle="popup-modal"
                        type="button"
                        class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:ring-gray-300 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600"
                        @click="closePanel"
                    >
                        No, cancel
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>
<script>
import axios from "Axios";
export default {
    props: ["flight"],

    methods: {
        async deleteFlight() {
            const res = await axios.delete("/manage/flights/" + this.flight.id);
            if (res.status === 200) {
                console.log("success");
                this.closePanel();
            }
        },
        closePanel() {
            this.$emit("closed");
        },
    },
};
</script>
